version: '3'
services:
  client:
    image: "nicolakoo/web-client"
    mem_limit: 128m
    networks:
      - basic-network
  apiserver:
    image: "nicolakoo/web-server"
    mem_limit: 128m
    networks:
      - basic-network
  nginx:
    restart: always
    depends_on:
      - client
      - apiServer
    image: "nicolakoo/web-nginx"
    mem_limit: 256m
    ports:
      - 80:80
    networks:
      - basic-network

networks:
  basic-network:
    driver: bridge
