version: '3'
services:
  client:
    image: "nicolakoo/web-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "nicolakoo/web-server"
    mem_limit: 128m
    hostname: api
  nginx:
    image: "nicolakoo/web-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"