version: '3'
services:
  client:
    image: "nicolakoo/web-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "nicolakoo/web-server"
    mem_limit: 128m
    hostname: api
  nginx:
    depends_on:
      - server
      - client
    image: "nicolakoo/web-nginx"
    mem_limit: 256m
    ports:
      - "80:80"